language: python
python:
  - "2.6"
  - "2.7"
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
# commands to install dependencies
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  - if [ $TRAVIS_PYTHON_VERSION = 2.6 ] ; then pip install "Django<1.7" "pylint<1.4.0" "astroid<1.3" "mechanize<=0.2.5"; fi
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi
  - pyflakes suseapi
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - codecov
cache:
  pip: true
