language: python
python:
  - "2.6"
  - "2.7"
sudo: false
# commands to install dependencies
install: 
  - if [ $TRAVIS_PYTHON_VERSION = 2.6 ] ; then pip install "Django<1.7" "pylint!=1.4.0" ; fi
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi || true
  - pyflakes suseapi
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
