language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
sudo: false
# commands to install dependencies
install: 
  - if [ $TRAVIS_PYTHON_VERSION = 2.6 ] ; then pip install "Django<1.7" "pylint!=1.4.0" ; fi
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi || true
  - pyflakes suseapi
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.3"
    - python: "3.2"
    - python: "pypy"
