language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
sudo: false
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi || true
  - pyflakes suseapi
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.3"
    - python: "3.2"
    - python: "pypy"
